Material:
  Name: PBR_BaseMaterial
  Parameters:
    BaseColor: [1.0, 1.0, 1.0]
    Metallic: 0.0
    Roughness: 0.0
    AmbientOcclusion: 1.0
    Opacity: 1.0
    DisplacementScale: 0.05
  Textures:
    BaseColor: Assets/Materials/Base/Base_Color.png
    Normal: Assets/Materials/Base/Base_NormalGL.png
    Roughness: Assets/Materials/Base/Base_Roughness.png
    AmbientOcclusion: Assets/Materials/Base/Base_AO.png
    Metallic: Assets/Materials/Base/Base_Metalness.png
    Displacement: Assets/Materials/Base/Base_Displacement.png
