Material:
  Name: STD_BaseMaterial
  Parameters:
    DiffuseColor: [1.0, 1.0, 1.0]
    SpecularColor: [1.0, 1.0, 1.0]
    AmbientColor: [1.0, 1.0, 1.0]
    EmissiveColor: [1.0, 1.0, 1.0]
    Shininess: 32.0
    Opacity: 1.0
  Textures:
    Diffuse: Assets/Materials/Base/STD/Base_DiffuseTexture.png
    Specular: Assets/Materials/Base/STD/Base_SpecularTexture.png
    Emissive: Assets/Materials/Base/STD/Base_EmissiveTexture.png
    Opacity: Assets/Materials/Base/STD/Base_OpacityTexture.png
