#include "CorePCH.hpp"

namespace Motion
{
    static constexpr bool sCenterWholeModel = false;
    static constexpr bool sCenterEachMesh   = true;

    /**
     * @brief Return a path that is not already taken by a file or directory.
     * @param originalPath The path to check for availability.
     * @return A path that is not already taken by a file or directory.
     * 
     * This function takes a path and checks if a file or directory with the same name
     * already exists. If it does, it appends "-copy" followed by a number (starting at 1)
     * to the stem of the path. It continues to increment the number until it finds a name that is
     * not already taken.
     */
    static std::filesystem::path GetAvailableCopyName(const std::filesystem::path& originalPath)
    {
        if (!std::filesystem::exists(originalPath))
            return originalPath;

        std::filesystem::path directory = originalPath.parent_path();
        std::string stem = originalPath.stem().string();
        std::string extension = originalPath.extension().string();

        int counter = 1;
        std::filesystem::path newPath;

        do
        {
            newPath = directory / (stem + "-copy" + (counter > 1 ? std::to_string(counter) : "") + extension);
            ++counter;
        } while (std::filesystem::exists(newPath));

        return newPath;
    }

    /**
     * @brief Generates box projection UVs for a given set of vertices.
     *
     * This function takes a set of vertices and generates box projection UVs for each vertex.
     * The generated UVs are then stored in the vertices' TexCoord field.
     *
     * Box projection UVs are generated by taking the absolute value of the vertex normal and
     * then using the two largest components of the normal to generate a UV coordinate.
     * The UV coordinates are then normalized to the range [0, 1] to ensure proper UV mapping.
     *
     * @param vertices The set of vertices to generate box projection UVs for.
     */
    void GenerateBoxProjectionUVs(std::vector<Vertex>& vertices)
    {
        if (vertices.empty()) return;

        glm::vec2 minUV(FLT_MAX), maxUV(-FLT_MAX);
        std::vector<glm::vec2> projected(vertices.size());

        for (size_t i = 0; i < vertices.size(); ++i) 
        {
            const glm::vec3& pos = vertices[i].Position;
            glm::vec3 n = glm::abs(glm::normalize(vertices[i].Normal));
            glm::vec2 uv;
            if (n.x >= n.y && n.x >= n.z)       uv = { pos.y, pos.z }; // YZ
            else if (n.y >= n.x && n.y >= n.z)  uv = { pos.x, pos.z }; // XZ
            else                                uv = { pos.x, pos.y }; // XY

            projected[i] = uv;
            minUV = glm::vec2(std::min<float>(minUV.x, uv.x), std::min<float>(minUV.y, uv.y));
            maxUV = glm::vec2(std::max<float>(maxUV.x, uv.x), std::max<float>(maxUV.y, uv.y));
        }

        glm::vec2 uvDifference = maxUV - minUV;
        glm::vec2 range = glm::vec2(std::max<float>(uvDifference.x, 1e-5f), std::max<float>(uvDifference.y, 1e-5f));
        
        for (size_t i = 0; i < vertices.size(); ++i)
            vertices[i].TexCoord = (projected[i] - minUV) / range;
    }

    static void GenerateNormals(std::vector<Vertex>& vertices, const std::vector<uint32_t>& indices)
    {
        for (auto& v : vertices) v.Normal = glm::vec3(0.0f);

        for (size_t i = 0; i < indices.size(); i += 3)
        {
            uint32_t I0 = indices[i];
            uint32_t I1 = indices[i + 1];
            uint32_t I2 = indices[i + 2];

            glm::vec3& P0 = vertices[I0].Position;
            glm::vec3& P1 = vertices[I1].Position;
            glm::vec3& P2 = vertices[I2].Position;

            glm::vec3 E1 = P1 - P0;
            glm::vec3 E2 = P2 - P0;

            glm::vec3 faceNormal = glm::normalize(glm::cross(E1, E2));

            vertices[I0].Normal += faceNormal;
            vertices[I1].Normal += faceNormal;
            vertices[I2].Normal += faceNormal;
        }

        for (auto& v : vertices)
            v.Normal = glm::normalize(v.Normal);
    }

    static std::string HashString(const std::string& input)
    {
        return std::format("{:X}", std::hash<std::string>{}(input));
    }

    namespace MikkTSpace
    {
        struct MeshMikkTSpaceAdapter
        {
            std::vector<Vertex>&        Vertices;
            const std::vector<uint32_t>& Indices;
        };

        static std::int32_t GetNumFaces(const SMikkTSpaceContext* context)
        {
            auto* adapter = static_cast<MeshMikkTSpaceAdapter*>(context->m_pUserData);
            return static_cast<std::int32_t>(adapter->Indices.size() / 3);
        }

        static std::int32_t GetNumVerticesOfFace(const SMikkTSpaceContext*, std::int32_t) { return 3; }

        static void GetPosition(const SMikkTSpaceContext* context, float pos[3], std::int32_t face, std::int32_t vert)
        {
            auto* adapter = static_cast<MeshMikkTSpaceAdapter*>(context->m_pUserData);
            std::int32_t idx = adapter->Indices[face * 3 + vert];
            const glm::vec3& p = adapter->Vertices[idx].Position;
            pos[0] = p.x; pos[1] = p.y; pos[2] = p.z;
        }

        static void GetNormal(const SMikkTSpaceContext* context, float norm[3], std::int32_t face, std::int32_t vert)
        {
            auto* adapter = static_cast<MeshMikkTSpaceAdapter*>(context->m_pUserData);
            std::int32_t idx = adapter->Indices[face * 3 + vert];
            const glm::vec3& n = adapter->Vertices[idx].Normal;
            norm[0] = n.x; norm[1] = n.y; norm[2] = n.z;
        }

        static void GetTexCoord(const SMikkTSpaceContext* context, float uv[2], std::int32_t face, std::int32_t vert)
        {
            auto* adapter       = static_cast<MeshMikkTSpaceAdapter*>(context->m_pUserData);
            std::int32_t idx    = adapter->Indices[face * 3 + vert];
            const glm::vec2& t  = adapter->Vertices[idx].TexCoord;
            uv[0] = t.x; uv[1]  = t.y;
        }

        static void SetTSpaceBasic(const SMikkTSpaceContext* context, const float tangent[4], float sign, std::int32_t face, std::int32_t vert)
        {
            auto* adapter = static_cast<MeshMikkTSpaceAdapter*>(context->m_pUserData);
            std::int32_t idx = adapter->Indices[face * 3 + vert];

            adapter->Vertices[idx].Tangent.x = tangent[0];
            adapter->Vertices[idx].Tangent.y = tangent[1];
            adapter->Vertices[idx].Tangent.z = tangent[2];
            adapter->Vertices[idx].Tangent.w = sign;

        }

        inline void GenerateTangents(std::vector<Vertex>& vertices, const std::vector<std::uint32_t>& indices)
        {
            MeshMikkTSpaceAdapter adapter{ vertices, indices };
            SMikkTSpaceInterface iface{};
            iface.m_getNumFaces          = GetNumFaces;
            iface.m_getNumVerticesOfFace = GetNumVerticesOfFace;
            iface.m_getPosition          = GetPosition;
            iface.m_getNormal            = GetNormal;
            iface.m_getTexCoord          = GetTexCoord;
            iface.m_setTSpaceBasic       = SetTSpaceBasic;
            iface.m_setTSpace            = nullptr;

            SMikkTSpaceContext context{};
            context.m_pInterface = &iface;
            context.m_pUserData  = &adapter;

            genTangSpaceDefault(&context);
        }
    }

    static bool Import(const std::filesystem::path& input, const std::filesystem::path& output, std::shared_ptr<ImportedResults>& outResults)
    {
        try
        {
            std::filesystem::path uniqueOutput = input;
            outResults->Name = input.filename().stem().string();
            outResults->FilePath = input;

            if (!output.empty())
            {
                const std::string modelFileName   = input.filename().string();
                const std::string modelFolderName = input.filename().stem().string();
                uniqueOutput = GetAvailableCopyName(output / modelFolderName) / modelFileName;

                if (!std::filesystem::exists(uniqueOutput))
                {
                    try
                    {
                        std::filesystem::copy_options options = std::filesystem::copy_options::recursive | std::filesystem::copy_options::overwrite_existing;
                        std::filesystem::create_directories(uniqueOutput.parent_path());
                        std::filesystem::copy(input, uniqueOutput, options);
                        MOTION_CORE_INFO("Copied all content from {} to {}", input.string(), uniqueOutput.string());
                    }
                    catch (const std::exception& e)
                    {
                        MOTION_CORE_ERROR("Failed to copy directory: {}", e.what());
                        return false;
                    }
                }

                outResults->FilePath = uniqueOutput;
            }

            Assimp::Importer importer{};
            constexpr std::uint32_t importFlags =
                aiProcess_Triangulate |
                aiProcess_GenSmoothNormals |
                aiProcess_CalcTangentSpace |
                aiProcess_ImproveCacheLocality |
                aiProcess_RemoveRedundantMaterials |
                aiProcess_ValidateDataStructure |
                aiProcess_JoinIdenticalVertices |
                aiProcess_PreTransformVertices |
                aiProcess_FindInvalidData |
                aiProcess_FindDegenerates |
                aiProcess_SortByPType |
                aiProcess_FlipUVs;

            const aiScene* scene = importer.ReadFile(uniqueOutput.string(), importFlags);
            if (!scene || (scene->mFlags & AI_SCENE_FLAGS_INCOMPLETE) || !scene->mRootNode)
            {
                MOTION_CORE_ERROR("Assimp Importer Error: {}", importer.GetErrorString());
                return false;
            }

            std::vector<bool> meshLoaded(scene->mNumMeshes, false);
            auto loadMesh = [&](std::uint32_t meshIndex, const aiMesh* mesh)
            {
                if (!mesh || meshLoaded[meshIndex]) return;
                meshLoaded[meshIndex] = true;

                auto [it, inserted] = outResults->Meshes.emplace(meshIndex, MeshAsset{});
                MeshAsset& m = it->second;
                m.ID         = meshIndex;

                aiMaterial* material    = scene->mMaterials[mesh->mMaterialIndex];
                aiString name           = material->GetName();
                
                const char* matName = name.Empty() ? std::format("MAT{}", mesh->mName.C_Str()).c_str() : name.C_Str();
                m.Name = std::format("{}_[{}]", mesh->mName.C_Str(), matName);

                const bool hasUVs      = mesh->HasTextureCoords(0);
                const bool hasNormals  = mesh->HasNormals();
                const bool hasTangents = mesh->HasTangentsAndBitangents();

                m.Vertices.clear();
                m.Vertices.reserve(mesh->mNumVertices);

                for (std::uint32_t i = 0; i < mesh->mNumVertices; ++i)
                {
                    Vertex vtx{};
                    vtx.Position = glm::vec3(mesh->mVertices[i].x, mesh->mVertices[i].y, mesh->mVertices[i].z);

                    vtx.TexCoord = hasUVs
                        ? glm::vec2(mesh->mTextureCoords[0][i].x, mesh->mTextureCoords[0][i].y)
                        : glm::vec2(0.f, 0.f);

                    vtx.Normal = hasNormals
                        ? glm::vec3(mesh->mNormals[i].x, mesh->mNormals[i].y, mesh->mNormals[i].z)
                        : glm::vec3(0.f, 0.f, 1.f);

                    if (hasTangents)
                    {
                        const glm::vec3 n(mesh->mNormals[i].x,    mesh->mNormals[i].y,    mesh->mNormals[i].z);
                        const glm::vec3 t(mesh->mTangents[i].x,   mesh->mTangents[i].y,   mesh->mTangents[i].z);
                        const glm::vec3 b(mesh->mBitangents[i].x, mesh->mBitangents[i].y, mesh->mBitangents[i].z);
                        
                        vtx.Tangent   = glm::vec4(t, 0.0f);
                        vtx.Bitangent = b;
                        vtx.Tangent.w = (glm::dot(glm::cross(n, t), b) < 0.f) ? -1.f : 1.f;
                    }
                    else
                    {
                        vtx.Tangent   = glm::vec4(1.f, 0.f, 0.f, 1.f);
                        vtx.Bitangent = glm::vec3(0.f, 1.f, 0.f);
                    }

                    m.Vertices.emplace_back(vtx);
                }

                m.Indices.clear();
                m.Indices.reserve(mesh->mNumFaces * 3);

                for (std::uint32_t f = 0; f < mesh->mNumFaces; ++f)
                {
                    const aiFace& face = mesh->mFaces[f];
                    if (face.mNumIndices != 3) continue;

                    const std::uint32_t i0 = face.mIndices[0];
                    const std::uint32_t i1 = face.mIndices[1];
                    const std::uint32_t i2 = face.mIndices[2];

                    if (i0 >= mesh->mNumVertices || i1 >= mesh->mNumVertices || i2 >= mesh->mNumVertices) continue;

                    m.Indices.emplace_back(i0);
                    m.Indices.emplace_back(i1);
                    m.Indices.emplace_back(i2);
                }

                if (!hasNormals)   GenerateNormals(m.Vertices, m.Indices);
                if (!hasUVs)       GenerateBoxProjectionUVs(m.Vertices);
                if (!hasTangents)  MikkTSpace::GenerateTangents(m.Vertices, m.Indices);
            };


            std::function<void(const aiNode*)> traverse = [&](const aiNode* node)
            {
                for (std::size_t i = 0; i < node->mNumMeshes; ++i)
                {
                    const std::uint32_t meshIdx = node->mMeshes[i];
                    loadMesh(meshIdx, scene->mMeshes[meshIdx]);
                }
                for (std::uint32_t i = 0; i < node->mNumChildren; ++i)
                    traverse(node->mChildren[i]);
            };

            traverse(scene->mRootNode);


            glm::vec3 modelMin( FLT_MAX );
            glm::vec3 modelMax(-FLT_MAX);

            for (auto& kv : outResults->Meshes)
            {
                const auto& verts = kv.second.Vertices;
                for (const auto& v : verts)
                {
                    modelMin.x = std::min<float>(modelMin.x, v.Position.x);
                    modelMin.y = std::min<float>(modelMin.y, v.Position.y);
                    modelMin.z = std::min<float>(modelMin.z, v.Position.z);

                    modelMax.x = std::max<float>(modelMax.x, v.Position.x);
                    modelMax.y = std::max<float>(modelMax.y, v.Position.y);
                    modelMax.z = std::max<float>(modelMax.z, v.Position.z);
                }
            }

            const glm::vec3 modelSize = modelMax - modelMin;
            const float     maxExtent = glm::compMax(glm::abs(modelSize));
            if (maxExtent <= std::numeric_limits<float>::epsilon())
            {
                MOTION_CORE_ERROR("Model has zero extent after import.");
                return false;
            }

            const glm::vec3 modelCenter  = 0.5f * (modelMin + modelMax);
            const float     targetSize   = 1.0f;              
            const float     uniformScale = targetSize / maxExtent;


            glm::vec3 newModelMin( (std::numeric_limits<float>::max)());
            glm::vec3 newModelMax(-(std::numeric_limits<float>::max)());

            for (auto& kv : outResults->Meshes)
            {
                auto& mesh  = kv.second;
                auto& verts = mesh.Vertices;

                glm::vec3 mn( (std::numeric_limits<float>::max)());
                glm::vec3 mx(-(std::numeric_limits<float>::max)());

                for (auto& v : verts)
                {
                    v.Position = (v.Position - modelCenter) * uniformScale;
                    v.Normal = glm::normalize(v.Normal);

                    mn.x = std::max<float>(mn.x, v.Position.x);
                    mn.y = std::max<float>(mn.y, v.Position.y);
                    mn.z = std::max<float>(mn.z, v.Position.z);

                    mx.x = std::min<float>(mx.x, v.Position.x);
                    mx.y = std::min<float>(mx.y, v.Position.y);
                    mx.z = std::min<float>(mx.z, v.Position.z);
                }

                mesh.MIN = mn;
                mesh.MAX = mx;

                newModelMin.x = std::min<float>(newModelMin.x, mn.x);
                newModelMin.y = std::min<float>(newModelMin.y, mn.y);
                newModelMin.z = std::min<float>(newModelMin.z, mn.z);

                newModelMax.x = std::max<float>(newModelMax.x, mx.x);
                newModelMax.y = std::max<float>(newModelMax.y, mx.y);
                newModelMax.z = std::max<float>(newModelMax.z, mx.z);
            }

            modelMin = newModelMin;
            modelMax = newModelMax;

            outResults->MIN = modelMin;
            outResults->MAX = modelMax;
            outResults->MeshCount = static_cast<std::uint32_t>(outResults->Meshes.size());
            
            return true;
        }
        catch (const std::exception& e)
        {
            MOTION_CORE_ERROR("{}", e.what());
            return false;
        }
    }

    /**
     * @brief Imports a model based on the given settings.
     * 
     * If the `ShouldExport` flag is set in the settings, the model will be exported to the given export path.
     * If the export path is set to "default", the model will be exported to the "Assets/Models" directory relative to the application path.
     * If the `ShouldExport` flag is not set, the model will not be exported.
     * 
     * @param settings The settings to import the model with.
     * @return A shared pointer to the imported results. If the import failed, nullptr will be returned.
     */
    std::shared_ptr<ImportedResults> Importer::ImportEntity(ImportSettings settings)
    {
        std::shared_ptr<ImportedResults> importedResults = std::make_shared<ImportedResults>();
        std::filesystem::path exportDirectory = settings.ShouldExport ? settings.ExportPath : std::filesystem::path{};
        if(!Import(settings.FilePath, exportDirectory, importedResults)) 
        {
            MOTION_CORE_ERROR("Failed to import model: {}", settings.FilePath.string());
            return nullptr;
        }

        return importedResults;  
    }
}

