Material:
  Name: MetalBaseMaterial
  Parameters:
    BaseColor: [1.0, 1.0, 1.0]
    Metallic: 0.0
    Roughness: 0.0
    Opacity: 1.0
  Textures:
    BaseColor: Assets/Materials/Base/Metal/Base_Color.png
    Normal: Assets/Materials/Base/Metal/Base_NormalGL.png
    Roughness: Assets/Materials/Base/Metal/Base_Roughness.png
    AmbientOcclusion: Assets/Materials/Base/Metal/Base_AO.png
    Metallic: Assets/Materials/Base/Metal/Base_Metalness.png
    Opacity: Assets/Materials/Base/Metal/Base_Opacity.png
    Emissive: Assets/Materials/Base/Metal/Base_Emissive.png
    Displacement: Assets/Materials/Base/Metal/Base_Displacement.png
