function(ConfigurePlatform)
    if(NOT CMAKE_SYSTEM_NAME)
        message(FATAL_ERROR "CMAKE_SYSTEM_NAME is not set. Please specify the target platform.")
    endif()

    message(STATUS "CMAKE_SYSTEM_NAME: ${CMAKE_SYSTEM_NAME}")
    if(CMAKE_SYSTEM_NAME STREQUAL "Windows")
        message(STATUS "Building for Windows")
        add_compile_definitions(MOTION_PLATFORM_WINDOWS)
        set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /bigobj")
        set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} /bigobj")
        set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /Zc:__cplusplus")
        set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} /Zc:__cplusplus")
        set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /D_CRT_SECURE_NO_WARNINGS")
        set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} /D_CRT_SECURE_NO_WARNINGS")
        set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /D_SCL_SECURE_NO_WARNINGS")
        set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} /D_SCL_SECURE_NO_WARNINGS")
        set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /D_CRT_NONSTDC_NO_DEPRECATE")
        set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} /D_CRT_NONSTDC_NO_DEPRECATE")
        set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /D_CRT_SECURE_NO_DEPRECATE")
        set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} /D_CRT_SECURE_NO_DEPRECATE")

    elseif(CMAKE_SYSTEM_NAME STREQUAL "Linux")
        message(STATUS "Building for Linux")
        add_compile_definitions(MOTION_PLATFORM_LINUX)
        set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fPIC")
        set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -fPIC")
        set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -pthread")
        set(CMAKE_SHARED_LINKER_FLAGS "${CMAKE_SHARED_LINKER_FLAGS} -pthread")
        set(CMAKE_MODULE_LINKER_FLAGS "${CMAKE_MODULE_LINKER_FLAGS} -pthread")
        set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wno-deprecated-declarations")
        set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -Wno-deprecated-declarations")
        set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wno-unused-parameter")
        set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -Wno-unused-parameter")
        set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wno-unused-variable")
        set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -Wno-unused-variable")
        set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wno-unused-function")
        set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -Wno-unused-function")
        set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wno-unused-but-set-variable")
        set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -Wno-unused-but-set-variable")
        set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wno-missing-field-initializers")
        set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -Wno-missing-field-initializers")
        set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wno-sign-compare")
        set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -Wno-sign-compare")
        message(WARNING "Motion Engine does not support Linux builds yet. This is a placeholder configuration.")

    elseif(CMAKE_SYSTEM_NAME STREQUAL "iOS")
        message(STATUS "Building for iOS")
        add_compile_definitions(MOTION_PLATFORM_IOS)
        set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fPIC")
        set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -fPIC")
        set(CMAKE_XCODE_ATTRIBUTE_IPHONEOS_DEPLOYMENT_TARGET "14.0" CACHE STRING "iOS Deployment Target" FORCE)
        set(CMAKE_XCODE_ATTRIBUTE_CLANG_CXX_LIBRARY "libc++" CACHE STRING "C++ Standard Library" FORCE)
        set(CMAKE_XCODE_ATTRIBUTE_CLANG_ENABLE_MODULES "YES" CACHE BOOL "Enable Clang Modules" FORCE)
        set(CMAKE_XCODE_ATTRIBUTE_CLANG_ENABLE_OBJC_ARC "YES" CACHE BOOL "Enable Objective-C ARC" FORCE)
        set(CMAKE_XCODE_ATTRIBUTE_CLANG_CXX_LANGUAGE_STANDARD "c++20" CACHE STRING "C++ Language Standard" FORCE)

    elseif(CMAKE_SYSTEM_NAME STREQUAL "Android")
        message(STATUS "Building for Android")
        if(NOT ANDROID_NDK)
            message(FATAL_ERROR "ANDROID_NDK is not set. Please specify the path to the Android NDK.")
        endif()
        add_compile_definitions(MOTION_PLATFORM_ANDROID)
        set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fPIC")
        set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -fPIC")
        set(CMAKE_ANDROID_ARCH_ABI "arm64-v8a" CACHE STRING "Android ABI" FORCE)
        set(CMAKE_ANDROID_STL_TYPE "c++_static" CACHE STRING "Android STL type" FORCE)
        set(CMAKE_ANDROID_NDK_TOOLCHAIN_VERSION "clang" CACHE STRING "Android NDK toolchain version" FORCE)
        set(CMAKE_ANDROID_API 21 CACHE STRING "Android API level" FORCE)
        message(WARNING "Motion Engine does not support Android builds yet. This is a placeholder configuration.")

    elseif(CMAKE_SYSTEM_NAME STREQUAL "Darwin")
        message(STATUS "Building for macOS")
        add_compile_definitions(MOTION_PLATFORM_MACOS)
        set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fPIC")
        set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -fPIC")
        set(CMAKE_OSX_DEPLOYMENT_TARGET "10.15" CACHE STRING "macOS Deployment Target" FORCE)
        set(CMAKE_XCODE_ATTRIBUTE_CLANG_CXX_LANGUAGE_STANDARD "c++20" CACHE STRING "C++ Language Standard" FORCE)
        set(CMAKE_XCODE_ATTRIBUTE_CLANG_CXX_LIBRARY "libc++" CACHE STRING "C++ Standard Library" FORCE)
        message(WARNING "Motion Engine does not support macOS builds yet. This is a placeholder configuration.")

    else()
        message(FATAL_ERROR "Unsupported platform: ${CMAKE_SYSTEM_NAME}")
        add_compile_definitions(MOTION_PLATFORM_UNKNOWN)
    endif()

endfunction()